name: archive

networks:
  archive_net:
    external: false

volumes:
  rabbit_data:
  postgres_data:
  db_dumps:

secrets:
  config:
    file: .secret/config.ini

services:
  rabbitmq:
    image: rabbitmq:3
    restart: always
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 5s
      retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - archive_net
  db:
    image: postgres:16
    restart: always
    container_name: 'db'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d archive -U archive"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=archive
      - POSTGRES_DB=archive
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'pg_dump -U archive -d archive -f /dumps/archive.sql'"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - db_dumps:/dumps
    networks:
      - archive_net
  archive:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - db
    restart: always
    secrets:
      - config
    environment:
      - CONFIG_FILE_PATH=/run/secrets/config
    volumes:
      - ${ARCHIVE_PATH}:/app/soundcloud
    networks:
      - archive_net
  backup:
    image: offen/docker-volume-backup:v2.48.0
    restart: always
    container_name: 'backup'
    environment:
      - BACKUP_CRON_EXPRESSION=0 3 * * *
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_FILENAME=archive-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_PRUNING_PREFIX=archive-backup-
      - BACKUP_COMPRESSION=gz
    volumes:
      - db_dumps:/backup/postgres-dumps:ro
      - rabbit_data:/backup/rabbit:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ARCHIVE_PATH}/backups:/archive
    networks:
      - archive_net